### ISSUE TITLE
文档就一两章

### ISSUE THREAD

**Issue by qijianchuan** [giiwa/giiwa#1]
文档不详细，api搞个中文的嘛。

**Comment by giiwa** [comment]
好👌

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："qijianchuan "<notifications@github.com>;
发送时间：2019年7月29日(星期一) 上午7:30
收件人："giiwa/giiwa" <giiwa@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[giiwa/giiwa] 文档就一两章 (#1)
-----------------------------------

 
文档不详细，api搞个中文的嘛。

**Comment by qijianchuan** [comment]
出个视频之内的最好，有什么功能呢，可以做网站不


 
---原始邮件---
发件人: "joe"<notifications@github.com>
发送时间: 2019年7月29日(星期一) 上午8:39
收件人: "giiwa/giiwa"<giiwa@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"qijianchuan"<406429544@qq.com>;
主题: Re: [giiwa/giiwa] 文档就一两章 (#1)


好👌 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 
 
 --------------原始邮件-------------- 
 发件人："qijianchuan "<notifications@github.com>; 
 发送时间：2019年7月29日(星期一) 上午7:30 
 收件人："giiwa/giiwa" <giiwa@noreply.github.com>; 
 抄送："Subscribed "<subscribed@noreply.github.com>; 
 主题：[giiwa/giiwa] 文档就一两章 (#1) 
 ----------------------------------- 
 
   
 文档不详细，api搞个中文的嘛。

**Comment by giiwa** [comment]
哈哈，太多了就怕写了。

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："qijianchuan "<notifications@github.com>;
发送时间：2019年7月29日(星期一) 下午3:29
收件人："giiwa/giiwa" <giiwa@noreply.github.com>;
抄送："joe "<joe.j@giiwa.org>;"Comment "<comment@noreply.github.com>;
主题：Re: [giiwa/giiwa] 文档就一两章 (#1)
-----------------------------------

 出个视频之内的最好，有什么功能呢，可以做网站不 
 
 
   
 ---原始邮件--- 
 发件人: "joe"<notifications@github.com> 
 发送时间: 2019年7月29日(星期一) 上午8:39 
 收件人: "giiwa/giiwa"<giiwa@noreply.github.com>; 
 抄送: "Author"<author@noreply.github.com>;"qijianchuan"<406429544@qq.com>; 
 主题: Re: [giiwa/giiwa] 文档就一两章 (#1) 
 
 
 好  
   
  ----------  
   
  该邮件从移动设备发送  
   
   
   
   
  --------------原始邮件--------------  
  发件人："qijianchuan "<notifications@github.com>;  
  发送时间：2019年7月29日(星期一) 上午7:30  
  收件人："giiwa/giiwa" <giiwa@noreply.github.com>;  
  抄送："Subscribed "<subscribed@noreply.github.com>;  
  主题：[giiwa/giiwa] 文档就一两章 (#1)  
  -----------------------------------  
   
     
  文档不详细，api搞个中文的嘛。

**Comment by giiwa** [comment]
https://wiki.giisoo.com/

**Comment by giiwa** [comment]
https://wiki.giisoo.com/
